# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'power_control_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 677)
        MainWindow.setStyleSheet("QMainWindow {background-color: #333333; color: #ffffff;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 411, 191))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_home1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_home1.setGeometry(QtCore.QRect(20, 40, 81, 31))
        self.pushButton_home1.setObjectName("pushButton_home1")
        self.pushButton_jogup1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_jogup1.setGeometry(QtCore.QRect(160, 40, 51, 41))
        self.pushButton_jogup1.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogup1.setObjectName("pushButton_jogup1")
        self.pushButton_jogdown1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_jogdown1.setEnabled(True)
        self.pushButton_jogdown1.setGeometry(QtCore.QRect(160, 90, 51, 41))
        self.pushButton_jogdown1.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogdown1.setObjectName("pushButton_jogdown1")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(160, 20, 47, 21))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_jogdownf1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_jogdownf1.setEnabled(True)
        self.pushButton_jogdownf1.setGeometry(QtCore.QRect(230, 100, 31, 31))
        self.pushButton_jogdownf1.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogdownf1.setObjectName("pushButton_jogdownf1")
        self.pushButton_jogupf1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_jogupf1.setGeometry(QtCore.QRect(230, 40, 31, 31))
        self.pushButton_jogupf1.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogupf1.setObjectName("pushButton_jogupf1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 47, 16))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lcdNumber1 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber1.setGeometry(QtCore.QRect(30, 90, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lcdNumber1.setFont(font)
        self.lcdNumber1.setStyleSheet("QLCDNumber{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.lcdNumber1.setObjectName("lcdNumber1")
        self.lineEdit_setpower1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_setpower1.setGeometry(QtCore.QRect(270, 60, 71, 31))
        self.lineEdit_setpower1.setObjectName("lineEdit_setpower1")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(280, 30, 111, 20))
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.pushButton_setpower = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_setpower.setGeometry(QtCore.QRect(350, 60, 41, 31))
        self.pushButton_setpower.setStyleSheet("QPushButton\n"
"{\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.pushButton_setpower.setObjectName("pushButton_setpower")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 411, 191))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"}")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_home2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_home2.setGeometry(QtCore.QRect(20, 50, 81, 31))
        self.pushButton_home2.setObjectName("pushButton_home2")
        self.pushButton_jogdown2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_jogdown2.setEnabled(True)
        self.pushButton_jogdown2.setGeometry(QtCore.QRect(150, 110, 51, 41))
        self.pushButton_jogdown2.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogdown2.setObjectName("pushButton_jogdown2")
        self.pushButton_jogup2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_jogup2.setGeometry(QtCore.QRect(150, 59, 51, 41))
        self.pushButton_jogup2.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogup2.setObjectName("pushButton_jogup2")
        self.pushButton_jogupf2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_jogupf2.setGeometry(QtCore.QRect(220, 60, 31, 31))
        self.pushButton_jogupf2.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogupf2.setObjectName("pushButton_jogupf2")
        self.pushButton_jogdownf2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_jogdownf2.setEnabled(True)
        self.pushButton_jogdownf2.setGeometry(QtCore.QRect(220, 120, 31, 31))
        self.pushButton_jogdownf2.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogdownf2.setObjectName("pushButton_jogdownf2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(220, 40, 47, 16))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(150, 40, 47, 16))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lcdNumber2 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber2.setGeometry(QtCore.QRect(30, 120, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lcdNumber2.setFont(font)
        self.lcdNumber2.setStyleSheet("QLCDNumber{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.lcdNumber2.setObjectName("lcdNumber2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(280, 50, 111, 20))
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.lineEdit_setpower2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_setpower2.setGeometry(QtCore.QRect(270, 80, 71, 31))
        self.lineEdit_setpower2.setObjectName("lineEdit_setpower2")
        self.pushButton_setpower_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_setpower_2.setGeometry(QtCore.QRect(350, 80, 41, 31))
        self.pushButton_setpower_2.setStyleSheet("QPushButton\n"
"{\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.pushButton_setpower_2.setObjectName("pushButton_setpower_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 430, 411, 191))
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"}")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_home3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_home3.setGeometry(QtCore.QRect(20, 50, 81, 31))
        self.pushButton_home3.setObjectName("pushButton_home3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(220, 30, 47, 16))
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.pushButton_jogdown3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_jogdown3.setEnabled(True)
        self.pushButton_jogdown3.setGeometry(QtCore.QRect(150, 100, 51, 41))
        self.pushButton_jogdown3.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogdown3.setObjectName("pushButton_jogdown3")
        self.pushButton_jogupf3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_jogupf3.setGeometry(QtCore.QRect(220, 50, 31, 31))
        self.pushButton_jogupf3.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogupf3.setObjectName("pushButton_jogupf3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(150, 30, 47, 16))
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.pushButton_jogup3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_jogup3.setGeometry(QtCore.QRect(150, 49, 51, 41))
        self.pushButton_jogup3.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogup3.setObjectName("pushButton_jogup3")
        self.pushButton_jogdownf3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_jogdownf3.setEnabled(True)
        self.pushButton_jogdownf3.setGeometry(QtCore.QRect(220, 110, 31, 31))
        self.pushButton_jogdownf3.setIconSize(QtCore.QSize(8, 16))
        self.pushButton_jogdownf3.setObjectName("pushButton_jogdownf3")
        self.lcdNumber3 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber3.setGeometry(QtCore.QRect(30, 110, 64, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lcdNumber3.setFont(font)
        self.lcdNumber3.setStyleSheet("QLCDNumber{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.lcdNumber3.setObjectName("lcdNumber3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(280, 50, 111, 20))
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 16px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.lineEdit_setpower_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_setpower_3.setGeometry(QtCore.QRect(270, 80, 71, 31))
        self.lineEdit_setpower_3.setObjectName("lineEdit_setpower_3")
        self.pushButton_setpower_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_setpower_3.setGeometry(QtCore.QRect(350, 80, 41, 31))
        self.pushButton_setpower_3.setStyleSheet("QPushButton\n"
"{\n"
"    font-size: 12px;\n"
"\n"
"}")
        self.pushButton_setpower_3.setObjectName("pushButton_setpower_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "642 nm laser"))
        self.pushButton_home1.setText(_translate("MainWindow", "Home"))
        self.pushButton_jogup1.setText(_translate("MainWindow", " ▲"))
        self.pushButton_jogdown1.setText(_translate("MainWindow", "▼"))
        self.label.setText(_translate("MainWindow", "Jog 5 º"))
        self.pushButton_jogdownf1.setText(_translate("MainWindow", "▼"))
        self.pushButton_jogupf1.setText(_translate("MainWindow", " ▲"))
        self.label_2.setText(_translate("MainWindow", "Jog1 º"))
        self.label_7.setText(_translate("MainWindow", "Set Power (uW)"))
        self.pushButton_setpower.setText(_translate("MainWindow", "Set"))
        self.groupBox_2.setTitle(_translate("MainWindow", "592 nm laser"))
        self.pushButton_home2.setText(_translate("MainWindow", "Home"))
        self.pushButton_jogdown2.setText(_translate("MainWindow", "▼"))
        self.pushButton_jogup2.setText(_translate("MainWindow", " ▲"))
        self.pushButton_jogupf2.setText(_translate("MainWindow", " ▲"))
        self.pushButton_jogdownf2.setText(_translate("MainWindow", "▼"))
        self.label_3.setText(_translate("MainWindow", "Jog1 º"))
        self.label_4.setText(_translate("MainWindow", "Jog 5 º"))
        self.label_8.setText(_translate("MainWindow", "Set Power (uW)"))
        self.pushButton_setpower_2.setText(_translate("MainWindow", "Set"))
        self.groupBox_3.setTitle(_translate("MainWindow", "775 nm laser"))
        self.pushButton_home3.setText(_translate("MainWindow", "Home"))
        self.label_5.setText(_translate("MainWindow", "Jog1 º"))
        self.pushButton_jogdown3.setText(_translate("MainWindow", "▼"))
        self.pushButton_jogupf3.setText(_translate("MainWindow", " ▲"))
        self.label_6.setText(_translate("MainWindow", "Jog 5 º"))
        self.pushButton_jogup3.setText(_translate("MainWindow", " ▲"))
        self.pushButton_jogdownf3.setText(_translate("MainWindow", "▼"))
        self.label_9.setText(_translate("MainWindow", "Set Power (uW)"))
        self.pushButton_setpower_3.setText(_translate("MainWindow", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
